time = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atlético-PA', 'Bahia', 'São Paulo', 'fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte preta', 'Atlético-GO')
print('===' * 10)
print(f'Lista de times do Brasileirão: {time}')
print('===' * 10)
print(f'Os 5 primeiros são {time[0:5]}')
print('===' * 10)
print(f'Os 4 últimos são {time[-4:]}')
print('===' * 10)
print(f'Times em ordem alfabética: {sorted(time)}')
print('===' * 10)
print('O {} está na {}ª posição'.format(time[7], time.index('Chapecoense') + 1))
