num = int(input('Quer ver até quanto? '))
n1 = 0
n2 = 1
cont = 2
print(n1, n2, end=' ')
while cont != num:
    n3 = n1 + n2
    print(n3, end=' ')
    if cont >= 2:
        n1 = n2
        n2 = n3
        cont += 1
