# n= float(input('Digite um valor: '))
# n= str(input('Digite um valor: '))
# n = bool(input('Digite um valor: '))
n = (input('Digite algo: '))
print(type(n))
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())